require("config")
require("config.options")
require("config.keymaps")
require("plugins.themes")
require("config.plugin_opts.cmake")
-- require("config.plugin_opts.catppuccian")
-- require("config.plugin_opts.cyberdream")
require("config.plugin_opts.lualine")
